Randy
keysight-eggplant/Sensetalk-Solutions pull request #14
Opened 2021-07-20 17:06 UTC by io-world

2021-07-20 17:06 UTC, io-world commented
Add Version to Color one

2021-07-20 18:19 UTC, seventhaxis requested changes
These solutions seem very similar. Could you condense them into a single solution?

2021-07-20 18:19 UTC, seventhaxis commented on background-colors.suite/Scripts/randy2.script
> +﻿//You know like an actual comment that tell you what the script is about
@io-world Randy, just make sure you include the connection process within your script(s). These are meant to be self-contained solutions.

2021-07-20 18:19 UTC, seventhaxis commented on background-colors.suite/Scripts/randy2.script
> +			LogSuccess	"Found:"&& SingleBGKey && "with Pixel count"&&CountColorMatrix.(TColor) &&"Color" && TColor && "Within Area" && FiiR
I'm not seeing any validation that the table values are listed in the proper vertical order. Let me know if I missed something.

2021-08-03 05:24 UTC, seventhaxis approved these changes

2021-08-03 05:24 UTC, merged